# Generated by Django 4.2.24 on 2025-09-04 06:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField(help_text="The message content submitted by the user")),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, help_text="When the message was created"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the message was processed by Celery task", null=True
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True, help_text="Celery task ID that processed this message", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("task_name", models.CharField(help_text="Name of the Celery task", max_length=255)),
                ("task_id", models.CharField(help_text="Celery task ID", max_length=255, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("STARTED", "Started"),
                            ("SUCCESS", "Success"),
                            ("FAILURE", "Failure"),
                            ("RETRY", "Retry"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                ("result", models.TextField(blank=True, help_text="Task result or error message", null=True)),
                (
                    "started_at",
                    models.DateTimeField(default=django.utils.timezone.now, help_text="When the task was started"),
                ),
                ("completed_at", models.DateTimeField(blank=True, help_text="When the task was completed", null=True)),
            ],
            options={
                "verbose_name": "Task Log",
                "verbose_name_plural": "Task Logs",
                "ordering": ["-started_at"],
            },
        ),
    ]
